services:
  esa2025:
    hostname: esa2025
    build: ./app_esa2025
    volumes:
      - ./app_esa2025/data:/app/data
      - ./app_esa2025:/app
    environment:
      PYTHONUNBUFFERED: '1'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.esa2025.rule=Host(`esa2025.craa.ecoshard.org`)'
      - 'traefik.http.routers.esa2025.entrypoints=websecure'
      - 'traefik.http.routers.esa2025.tls=true'
      - 'traefik.http.routers.esa2025.tls.certresolver=letsencrypt'
      - 'traefik.http.services.esa2025.loadbalancer.server.port=8000'
    depends_on:
      - reverse-proxy
    networks:
      - web
    tty: true
    stdin_open: true

  ipbes-selection:
    hostname: ipbes-selection
    build: ./app_ipbes_selection
    volumes:
      - ./ipbes_selection/data:/app/data
      - ./ipbes_selection:/app
    environment:
      PYTHONUNBUFFERED: '1'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ipbes.rule=Host(`ipbes-selection.craa.ecoshard.org`)'
      - 'traefik.http.routers.ipbes.entrypoints=websecure'
      - 'traefik.http.routers.ipbes.tls=true'
      - 'traefik.http.routers.ipbes.tls.certresolver=letsencrypt'
      - 'traefik.http.services.ipbes.loadbalancer.server.port=8000'
    depends_on:
      - reverse-proxy
    networks:
      - web
    tty: true
    stdin_open: true

  reverse-proxy:
    image: traefik:v2.11
    container_name: traefik
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.web.http.redirections.entryPoint.to=websecure'
      - '--entryPoints.web.http.redirections.entryPoint.scheme=https'
      - '--entryPoints.websecure.address=:443'
      - '--certificatesResolvers.letsencrypt.acme.httpChallenge=true'
      - '--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web'
      - '--certificatesResolvers.letsencrypt.acme.email=rich@springinnovate.org'
      - '--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './letsencrypt:/letsencrypt'
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: web
