#docker build -f Dockerfile.crawler -t crawl_env . && docker run --rm -it -v %CD%:/app crawl_env
FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    alembic \
    beautifulsoup4 \
    dotenv \
    lxml \
    openai \
    playwright \
    pyyaml \
    requests \
    sqlalchemy \
    tqdm \
    && python -m playwright install --with-deps chromium

CMD ["bash"]
