"""adding an entities analyzed entry

Revision ID: 4c4b792a3222
Revises: c6db1bf71d10
Create Date: 2025-12-03 00:48:08.000042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c4b792a3222"
down_revision: Union[str, Sequence[str], None] = "c6db1bf71d10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "entities_analyzed",
                sa.JSON(),
                nullable=False,
                server_default="[]",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.drop_column("entities_analyzed")

    # ### end Alembic commands ###
