"""adding a entitybio table

Revision ID: a684db4fd1ff
Revises: 62d5a9dfde6a
Create Date: 2025-12-04 03:14:47.209719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a684db4fd1ff"
down_revision: Union[str, Sequence[str], None] = "62d5a9dfde6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_bios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "name", name="uq_entity_bios_type_name"),
    )
    with op.batch_alter_table("entity_bios", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_bios_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_entity_bios_type"), ["type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entity_bios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_bios_type"))
        batch_op.drop_index(batch_op.f("ix_entity_bios_name"))

    op.drop_table("entity_bios")
    # ### end Alembic commands ###
